# Document:
# http://simiki.org/docs/configuration.html

url: http://zhbzz2007.github.io
title: 老顽童的wiki
keywords: wiki, python, machine learning
description: wiki-zhb is a wiki for zhbzz2007.
author: zhbzz2007

root: /
source: content
destination: output
themes_dir: themes
theme: simple

default_ext: md
pygments: true
debug: false

deploy:
  - type: git
    remote: origin
    branch: master
